[build]
  publish = "mikroar-form-app/public"
  command = ""

[functions]
  directory = "mikroar-form-app/netlify/functions"

# --- API → Netlify Functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true
  conditions = { Host = ["form.mikroar.com", "anket.mikroar.com"] }

# --- Kısa URL → aynı HTML (form.html)
[[redirects]]
  from = "/f/*"
  to   = "/form.html"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

# --- form.mikroar.com varsayılanı
[[redirects]]
  from = "/"
  to   = "/form.html"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

# --- anket.mikroar.com varsayılanı (yönetim)
[[redirects]]
  from = "/"
  to   = "/admin.html"
  status = 200
  conditions = { Host = ["anket.mikroar.com"] }
