# ---------- BUILD ----------
[build]
  publish = "mikroar-form-app/public"

# Serverless Functions klasörü (repo kökünden yol)
[functions]
  directory = "netlify/functions"

# ---------- API redirect'leri ----------
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# ---------- Edge Function eşlemeleri ----------
# form.html isteklerini Edge SSR ile işle
[[edge_functions]]
  path = "/form.html"
  function = "form-ssr"

# kısa link /f/* için de aynı Edge SSR devrede
[[edge_functions]]
  path = "/f/*"
  function = "form-ssr"

  [build]
  publish = "mikroar-form-app/public"

[functions]
  directory = "mikroar-form-app/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[edge_functions]]
  path = "/form.html"
  function = "form-ssr"

[[edge_functions]]
  path = "/f/*"
  function = "form-ssr"
