[build]
  publish = "mikroar-form-app/public"

[functions]
  directory = "mikroar-form-app/netlify/functions"

############################
# form.mikroar.com
############################

# API -> Netlify Functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

# Kısa link: /f/:code  (URL aynı kalsın, form.html içerik dönsün)
# Bu kural mutlaka catch-all’dan ÖNCE olmalı.
[[redirects]]
  from = "/f/*"
  to   = "/form.html"
  status = 200
  force  = true
  conditions = { Host = ["form.mikroar.com"] }

# Catch-all: her şey form.html
[[redirects]]
  from = "/*"
  to   = "/form.html"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

############################
# anket.mikroar.com
############################

# API -> Netlify Functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  conditions = { Host = ["anket.mikroar.com"] }

# Tüm yollar admin arayüzüne
[[redirects]]
  from = "/*"
  to   = "/admin.html"
  status = 200
  conditions = { Host = ["anket.mikroar.com"] }
