[build]
  publish = "mikroar-form-app/public"
  command = ""

[functions]
  directory = "mikroar-form-app/netlify/functions"

# Sadece form şemasını okumak için:
[[redirects]]
  from = "/api/forms"
  to   = "/.netlify/functions/forms"
  status = 200
# Admin CRUD isteklerini forms-admin fonksiyonuna gönder
[[redirects]]
  from = "/api/admin/forms"
  to   = "/.netlify/functions/forms-admin"
  status = 200
# Kalan tüm /api/* çağrılarını aynı isimli fonksiyona gönder:
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

    [[headers]]
  for = "/form.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/form.html"
  [headers.values]
    Cache-Control = "no-cache"
    [[redirects]]
  from = "/s/:code"
  to   = "/.netlify/functions/go?code=:code"
  status = 200
  [[redirects]]
  from = "/share/:slug"
  to   = "/.netlify/functions/share?slug=:slug"
  status = 200
  # --- anket.mikroar.com -> /admin ---
[[redirects]]
  from = "/"
  to = "/admin"
  status = 301
  force = true
  conditions = { Host = ["anket.mikroar.com"] }

# admin altındaki tüm yollar düzgün çalışsın
[[redirects]]
  from = "/*"
  to = "/admin/:splat"
  status = 200
  conditions = { Host = ["anket.mikroar.com"] }

# --- form.mikroar.com -> /form.html ---
# API çağrılarını bozmayalım
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

# köke ve diğer tüm yollara /form.html döndür (query string korunur)
[[redirects]]
  from = "/"
  to = "/form.html"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

[[redirects]]
  from = "/*"
  to = "/form.html"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }
