# =========================
# Netlify config — MIKROAR
# =========================

[build]
  publish  = "mikroar-form-app/public"
  command  = ""

[functions]
  directory = "mikroar-form-app/netlify/functions"

# ---------- ortak güvenlik / önbellek ----------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/form.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# =========================
# anket.mikroar.com  (admin)
# =========================
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  conditions = { Host = ["anket.mikroar.com"] }

[[redirects]]
  from = "/*"
  to   = "/admin.html"
  status = 200
  conditions = { Host = ["anket.mikroar.com"] }

# =========================
# form.mikroar.com  (kamu formu)
# =========================
# API
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

# Kısa link: /f/101010  -> form.html (URL değişmeden)
[[redirects]]
  from = "/f/*"
  to   = "/form.html"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/form.html"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }
