[build]
  publish = "mikroar-form-app/public"
  command = ""

[functions]
  directory = "mikroar-form-app/netlify/functions"

# --- API / Functions (tüm hostlarda) ---
[[redirects]]
  from = "/api/forms"
  to   = "/.netlify/functions/forms"
  status = 200

[[redirects]]
  from = "/api/admin/forms"
  to   = "/.netlify/functions/forms-admin"
  status = 200

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# --- Kısa link fonksiyonları ---
[[redirects]]
  from = "/s/:code"
  to   = "/.netlify/functions/go?code=:code"
  status = 200

[[redirects]]
  from = "/share/:slug"
  to   = "/.netlify/functions/share?slug=:slug"
  status = 200

# --- Güvenlik / Önbellek header'ları ---
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/form.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/form.html"
  [headers.values]
    Cache-Control = "no-cache"

# =========================
# anket.mikroar.com  →  admin.html
# (tam URL ile domaine özel kural)
# =========================

# /form.html bu domainde görünmesin
[[redirects]]
  from = "https://anket.mikroar.com/form.html"
  to   = "/admin.html"
  status = 301

# kök ve diğer tüm yollar admin.html
[[redirects]]
  from = "https://anket.mikroar.com/"
  to   = "/admin.html"
  status = 200

[[redirects]]
  from = "https://anket.mikroar.com/*"
  to   = "/admin.html"
  status = 200

# =========================
# form.mikroar.com  →  form.html
# =========================

# admin yolları bu domainde görünmesin
[[redirects]]
  from = "https://form.mikroar.com/admin"
  to   = "/form.html"
  status = 301

[[redirects]]
  from = "https://form.mikroar.com/admin.html"
  to   = "/form.html"
  status = 301

# kök ve kalan her şey form.html
[[redirects]]
  from = "https://form.mikroar.com/"
  to   = "/form.html"
  status = 200

[[redirects]]
  from = "https://form.mikroar.com/*"
  to   = "/form.html"
  status = 200
