[build]
  publish = "mikroar-form-app/public"
  command = ""

[functions]
  directory = "mikroar-form-app/netlify/functions"

# --- API / Functions (öncelik en üstte) ---
[[redirects]]
  from = "/api/forms"
  to   = "/.netlify/functions/forms"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/forms"
  to   = "/.netlify/functions/forms-admin"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force = true

# --- Kısa link fonksiyonları ---
[[redirects]]
  from = "/s/:code"
  to   = "/.netlify/functions/go?code=:code"
  status = 200

[[redirects]]
  from = "/share/:slug"
  to   = "/.netlify/functions/share?slug=:slug"
  status = 200

# --- Güvenlik / Önbellek ---
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/form.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/form.html"
  [headers.values]
    Cache-Control = "no-cache"

# --- route yardımcıları ---
# / → index.html (index de hosta göre gerekli sayfaya yönlendiriyor)
[[redirects]]
  from = "/"
  to   = "/index.html"
  status = 200

# admin kısa yol
[[redirects]]
  from = "/admin"
  to   = "/admin.html"
  status = 200
  # ... mevcut ayarlarınızın altına ekleyin
[[edge_functions]]
function = "form-ssr"
path = "/form.html"

# form.mikroar.com hostu rewrite ediyor ama Edge Function yine form.html üzerinde çalışacak.
[[edge_functions]]
function = "form-ssr"
path = "/form.html"

# İsteğe bağlı: form.html altındaki varyantlar için de çalışsın
[[edge_functions]]
function = "form-ssr"
path = "/form.html/*"
