[build]
  publish = "mikroar-form-app/public"

[functions]
  directory = "mikroar-form-app/netlify/functions"

# ---------- form.mikroar.com ----------
# API -> Functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

# KISA LİNK: /f/101010  (URL SABİT KALSIN, form.html döndür)
# Bu kural MUTLAKA genel kuraldan ÖNCE olacak.
[[redirects]]
  from = "/f/*"
  to   = "/form.html"
  status = 200
  force  = true
  conditions = { Host = ["form.mikroar.com"] }
# form.mikroar.com → kısa linkler
[[redirects]]
  from = "/f/*"
  to   = "/form.html"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }
# Varsayılan: her şey form.html (GENEL kural)
[[redirects]]
  from = "/*"
  to   = "/form.html"
  status = 200
  conditions = { Host = ["form.mikroar.com"] }

# (İstiyorsan)
# [[edge_functions]]
#   function = "form-ssr"
#   path = "/form.html"

# ---------- anket.mikroar.com ----------
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  conditions = { Host = ["anket.mikroar.com"] }

[[redirects]]
  from = "/*"
  to   = "/admin.html"
  status = 200
  conditions = { Host = ["anket.mikroar.com"] }
