# ---------- BUILD ----------
[build]
  publish = "mikroar-form-app/public"

# Serverless Functions klasörü
[functions]
  directory = "mikroar-form-app/netlify/functions"
  node_bundler = "esbuild"

# /api/* -> /.netlify/functions/*
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# ---------- Edge Function eşleşmesi YALNIZCA kısa link için ----------
[[edge_functions]]
  path = "/f/*"
  function = "form-ssr"

# Sadece anket.mikroar.com için kökten admin.html'e yönlendir
[[redirects]]
  from = "/"
  to = "/admin.html"
  status = 200
  force = true
  conditions = { Host = ["anket.mikroar.com"] }
